In [6]:
import pandas as pd
import numpy as np

In [51]:
data = pd.read_csv("./raw/health/centros_de_salud.csv")
data=data.iloc[1:,:].reset_index().drop('index',axis=1)
data

             Demarcación territorial NUMERO_CENTROS
0                   Ciudad de México            578
1                De consulta externa            496
2         De hospitalización general             41
3   De hospitalización especializada             41
4                     Álvaro Obregón             29
..                               ...            ...
67  De hospitalización especializada              2
68                   No especificado             81
69               De consulta externa             49
70        De hospitalización general             16
71  De hospitalización especializada             16

[72 rows x 2 columns]

In [52]:
excluir = [
    "De consulta externa",
    "De hospitalización general",
    "De hospitalización especializada",
    "No especificado"
]

centros_salud = data[~data["Demarcación territorial"].isin(excluir)].reset_index(drop=True)
centros_salud

   Demarcación territorial NUMERO_CENTROS
0         Ciudad de México            578
1           Álvaro Obregón             29
2             Azcapotzalco             27
3            Benito Juárez             25
4                 Coyoacán             27
5    Cuajimalpa de Morelos             14
6               Cuauhtémoc             70
7        Gustavo A. Madero             58
8                Iztacalco             11
9               Iztapalapa             65
10  La Magdalena Contreras             14
11          Miguel Hidalgo             27
12              Milpa Alta             16
13                 Tláhuac             21
14                 Tlalpan             40
15     Venustiano Carranza             30
16              Xochimilco             23

In [53]:
centros_salud["NUMERO_CENTROS"] = centros_salud['NUMERO_CENTROS'].astype(int)
centros_salud

   Demarcación territorial  NUMERO_CENTROS
0         Ciudad de México             578
1           Álvaro Obregón              29
2             Azcapotzalco              27
3            Benito Juárez              25
4                 Coyoacán              27
5    Cuajimalpa de Morelos              14
6               Cuauhtémoc              70
7        Gustavo A. Madero              58
8                Iztacalco              11
9               Iztapalapa              65
10  La Magdalena Contreras              14
11          Miguel Hidalgo              27
12              Milpa Alta              16
13                 Tláhuac              21
14                 Tlalpan              40
15     Venustiano Carranza              30
16              Xochimilco              23

In [54]:
centros_salud.loc[0, "NUMERO_CENTROS"] = centros_salud.iloc[1:,:]['NUMERO_CENTROS'].sum()
centros_salud

   Demarcación territorial  NUMERO_CENTROS
0         Ciudad de México             497
1           Álvaro Obregón              29
2             Azcapotzalco              27
3            Benito Juárez              25
4                 Coyoacán              27
5    Cuajimalpa de Morelos              14
6               Cuauhtémoc              70
7        Gustavo A. Madero              58
8                Iztacalco              11
9               Iztapalapa              65
10  La Magdalena Contreras              14
11          Miguel Hidalgo              27
12              Milpa Alta              16
13                 Tláhuac              21
14                 Tlalpan              40
15     Venustiano Carranza              30
16              Xochimilco              23

In [55]:
centros_salud['NUMERO_CENTROS_PORCENTAJE']=centros_salud["NUMERO_CENTROS"]/centros_salud["NUMERO_CENTROS"][0]
centros_salud

   Demarcación territorial  NUMERO_CENTROS  NUMERO_CENTROS_PORCENTAJE
0         Ciudad de México             497                   1.000000
1           Álvaro Obregón              29                   0.058350
2             Azcapotzalco              27                   0.054326
3            Benito Juárez              25                   0.050302
4                 Coyoacán              27                   0.054326
5    Cuajimalpa de Morelos              14                   0.028169
6               Cuauhtémoc              70                   0.140845
7        Gustavo A. Madero              58                   0.116700
8                Iztacalco              11                   0.022133
9               Iztapalapa              65                   0.130785
10  La Magdalena Contreras              14                   0.028169
11          Miguel Hidalgo              27                   0.054326
12              Milpa Alta              16                   0.032193
13                 Tláhuac              21                   0.042254
14                 Tlalpan              40                   0.080483
15     Venustiano Carranza              30                   0.060362
16              Xochimilco              23                   0.046278

In [56]:
centros_salud.to_csv("./output/health_centers.csv", index=False)