In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("./raw/transportation/transporte_publico - Hoja 1.csv")
data

,Alcaldias,Lineas de metro,Lineas de metrobus,Estaciones Ecobici,LineasRTP
0,Álvaro Obregón,3,1,17,28
1,Azcapotzalco,2,2,28,9
2,Benito Juárez,4,3,213,18
3,Coyoacán,2,2,37,31
4,Cuajimalpa de Morelos,0,0,0,13
5,Cuauhtémoc,7,5,243,13
6,Gustavo A. Madero,5,5,0,18
7,Iztacalco,5,3,0,9
8,Iztapalapa,3,2,0,22
9,La Magdalena Contreras,0,0,0,5
10,Miguel Hidalgo,4,2,139,23
11,Milpa Alta,0,0,0,6
12,Tláhuac,1,0,0,9
13,Tlalpan,0,2,0,24
14,Venustiano Carranza,6,2,0,9
15,Xochimilco,0,1,0,15

In [5]:
new_row_df = pd.DataFrame({"Alcaldias": ["Total de la entidad Ciudad de México"], "Lineas de metro": [data["Lineas de metro"].sum()],"Lineas de metrobus": [data["Lineas de metrobus"].sum()],"Estaciones Ecobici": [data["Estaciones Ecobici"].sum()],"LineasRTP": [data["LineasRTP"].sum()]})
numero_transporte = pd.concat([new_row_df,data], ignore_index=False).reset_index().drop("index",axis=1)
numero_transporte

,Alcaldias,Lineas de metro,Lineas de metrobus,Estaciones Ecobici,LineasRTP
0,Total de la entidad Ciudad de México,42,30,677,252
1,Álvaro Obregón,3,1,17,28
2,Azcapotzalco,2,2,28,9
3,Benito Juárez,4,3,213,18
4,Coyoacán,2,2,37,31
5,Cuajimalpa de Morelos,0,0,0,13
6,Cuauhtémoc,7,5,243,13
7,Gustavo A. Madero,5,5,0,18
8,Iztacalco,5,3,0,9
9,Iztapalapa,3,2,0,22
10,La Magdalena Contreras,0,0,0,5
11,Miguel Hidalgo,4,2,139,23
12,Milpa Alta,0,0,0,6
13,Tláhuac,1,0,0,9
14,Tlalpan,0,2,0,24
15,Venustiano Carranza,6,2,0,9
16,Xochimilco,0,1,0,15

In [6]:
for i in range(1,len(numero_transporte.columns)):
    index=numero_transporte.columns[i]
    numero_transporte[index+"_PORCENTAJE_MUN"]=numero_transporte[index]/numero_transporte[index][0]
numero_transporte

,Alcaldias,Lineas de metro,Lineas de metrobus,Estaciones Ecobici,LineasRTP,Lineas de metro_PORCENTAJE_MUN,Lineas de metrobus_PORCENTAJE_MUN,Estaciones Ecobici_PORCENTAJE_MUN,LineasRTP_PORCENTAJE_MUN
0,Total de la entidad Ciudad de México,42,30,677,252,1.000000,1.000000,1.000000,1.000000
1,Álvaro Obregón,3,1,17,28,0.071429,0.033333,0.025111,0.111111
2,Azcapotzalco,2,2,28,9,0.047619,0.066667,0.041359,0.035714
3,Benito Juárez,4,3,213,18,0.095238,0.100000,0.314623,0.071429
4,Coyoacán,2,2,37,31,0.047619,0.066667,0.054653,0.123016
5,Cuajimalpa de Morelos,0,0,0,13,0.000000,0.000000,0.000000,0.051587
6,Cuauhtémoc,7,5,243,13,0.166667,0.166667,0.358936,0.051587
7,Gustavo A. Madero,5,5,0,18,0.119048,0.166667,0.000000,0.071429
8,Iztacalco,5,3,0,9,0.119048,0.100000,0.000000,0.035714
9,Iztapalapa,3,2,0,22,0.071429,0.066667,0.000000,0.087302
10,La Magdalena Contreras,0,0,0,5,0.000000,0.000000,0.000000,0.019841
11,Miguel Hidalgo,4,2,139,23,0.095238,0.066667,0.205318,0.091270
12,Milpa Alta,0,0,0,6,0.000000,0.000000,0.000000,0.023810
13,Tláhuac,1,0,0,9,0.023810,0.000000,0.000000,0.035714
14,Tlalpan,0,2,0,24,0.000000,0.066667,0.000000,0.095238
15,Venustiano Carranza,6,2,0,9,0.142857,0.066667,0.000000,0.035714
16,Xochimilco,0,1,0,15,0.000000,0.033333,0.000000,0.059524

In [7]:
numero_transporte.to_csv("./output/transportation.csv", index=False)