In [191]:
import pandas as pd
from functools import reduce

In [ ]:
data_budget=pd.read_csv("./output/budget.csv")
data_housing=pd.read_csv("./output/housing_state.csv")
data_green_spaces=pd.read_csv("./output/green_spaces.csv")
data_health_centers=pd.read_csv("./output/health_centers.csv")
data_hotels=pd.read_csv("./output/hotels.csv")
data_restaurant=pd.read_csv("./output/restaurant.csv")
data_transportation=pd.read_csv("./output/transportation.csv")
data_security=pd.read_csv("./output/security_everyone.csv")

In [193]:
data_budget=data_budget.sort_values(by="Alcaldia").rename(columns={"Alcaldia":"ALCALDIA"})
data_housing=data_housing.iloc[1:,:].sort_values(by="NOM_MUN").rename(columns={"NOM_MUN":"ALCALDIA"})
data_green_spaces=data_green_spaces.iloc[1:,:].sort_values(by="Alcaldía").rename(columns={"Alcaldía":"ALCALDIA"})
data_health_centers=data_health_centers.iloc[1:,:].sort_values(by="Demarcación territorial").rename(columns={"Demarcación territorial":"ALCALDIA"})
data_restaurant=data_restaurant.sort_values(by="alcaldia").rename(columns={"alcaldia":"ALCALDIA"})
data_transportation=data_transportation.iloc[1:,:].sort_values(by="Alcaldias").rename(columns={"Alcaldias":"ALCALDIA"})
data_security=data_security.sort_values(by="NOM_MUN").rename(columns={"NOM_MUN":"ALCALDIA"})

In [194]:
merged_data=data_budget
merge=[data_housing,data_green_spaces,data_health_centers,data_restaurant,data_transportation,data_security]
for i in range(0,len(merge)):
    merged_data=merged_data.merge(merge[i], on="ALCALDIA")
merged_data

,ALCALDIA,venta,Renta,venta_PORCENTAJE_MUN,Renta_PORCENTAJE_MUN,PROM_OCUP,VPH_PISODT,VPH_PISOTI,VPH_C_ELEC,VPH_S_ELEC,...,Lineas de metro,Lineas de metrobus,Estaciones Ecobici,LineasRTP,Lineas de metro_PORCENTAJE_MUN,Lineas de metrobus_PORCENTAJE_MUN,Estaciones Ecobici_PORCENTAJE_MUN,LineasRTP_PORCENTAJE_MUN,General_Security_SCORE,normalized
0,Azcapotzalco,2345500.0,12267.0,0.239483,0.535420,3.21,133490,334,133798,38,...,2,2,28,9,0.047619,0.066667,0.041359,0.035714,391,0.182243
1,Benito Juárez,4855384.0,16429.0,0.495751,0.717079,2.46,175564,129,175762,29,...,4,3,213,18,0.095238,0.100000,0.314623,0.071429,566,1.000000
2,Coyoacán,5912716.0,13644.0,0.603708,0.595522,3.20,190701,450,191126,61,...,2,2,37,31,0.047619,0.066667,0.054653,0.123016,458,0.495327
3,Cuajimalpa de Morelos,8081067.0,15641.0,0.825104,0.682685,3.60,59692,591,60308,31,...,0,0,0,13,0.000000,0.000000,0.000000,0.051587,482,0.607477
4,Cuauhtémoc,5226536.0,22911.0,0.533647,1.000000,2.75,195486,256,195726,82,...,7,5,243,13,0.166667,0.166667,0.358936,0.051587,482,0.607477
5,Gustavo A. Madero,5049058.0,9757.0,0.515525,0.425865,3.42,338175,1466,339504,160,...,5,5,0,18,0.119048,0.166667,0.000000,0.071429,385,0.154206
6,Iztacalco,2650977.0,10057.0,0.270673,0.438959,3.43,117149,282,117396,52,...,5,3,0,9,0.119048,0.100000,0.000000,0.035714,407,0.257009
7,Iztapalapa,4150000.0,10459.0,0.423729,0.456506,3.61,500645,2872,503261,300,...,3,2,0,22,0.071429,0.066667,0.000000,0.087302,374,0.102804
8,La Magdalena Contreras,7575000.0,11671.0,0.773432,0.509406,3.62,67362,618,67911,76,...,0,0,0,5,0.000000,0.000000,0.000000,0.019841,460,0.504673
9,Miguel Hidalgo,9794003.0,21326.0,1.000000,0.930819,2.81,144245,228,144483,45,...,4,2,139,23,0.095238,0.066667,0.205318,0.091270,487,0.630841
10,Milpa Alta,3673255.0,16000.0,0.375051,0.698355,3.90,38001,1027,38879,151,...,0,0,0,6,0.000000,0.000000,0.000000,0.023810,449,0.453271
11,Tlalpan,4479429.0,16000.0,0.457364,0.698355,3.44,200099,1801,201635,274,...,0,2,0,24,0.000000,0.066667,0.000000,0.095238,444,0.429907
12,Tláhuac,2651450.0,17938.0,0.270722,0.782943,3.67,104766,1908,106424,243,...,1,0,0,9,0.023810,0.000000,0.000000,0.035714,352,0.000000
13,Venustiano Carranza,4675000.0,10316.0,0.477333,0.450264,3.26,134924,343,135248,53,...,6,2,0,9,0.142857,0.066667,0.000000,0.035714,454,0.476636
14,Xochimilco,2992341.0,15183.0,0.305528,0.662695,3.74,114202,2741,116707,248,...,0,1,0,15,0.000000,0.033333,0.000000,0.059524,364,0.056075
15,Álvaro Obregón,6578833.0,15302.0,0.671721,0.667889,3.45,217550,1153,218704,74,...,3,1,17,28,0.071429,0.033333,0.025111,0.111111,428,0.355140

In [195]:
merged_data.columns

Index(['ALCALDIA', 'venta', 'Renta', 'venta_PORCENTAJE_MUN',
       'Renta_PORCENTAJE_MUN', 'PROM_OCUP', 'VPH_PISODT', 'VPH_PISOTI',
       'VPH_C_ELEC', 'VPH_S_ELEC', 'VPH_AEASP', 'VPH_AGUAFV', 'VPH_DRENAJ',
       'VPH_NODREN', 'VPH_SNBIEN', 'VPH_REFRI', 'VPH_LAVAD', 'VPH_HMICRO',
       'VPH_AUTOM', 'VPH_MOTO', 'VPH_BICI', 'VPH_RADIO', 'VPH_TV', 'VPH_PC',
       'VPH_TELEF', 'VPH_CEL', 'VPH_INTER', 'VPH_STVP', 'VPH_SPMVPI',
       'VPH_CVJ', 'BUEN_EDO', 'Habitantes (Año 2015)', 'Superficie (m²)',
       'Superficie por habitante (m²)', 'Habitantes (Año 2015)_PORCENTAJE',
       'Superficie (m²)_PORCENTAJE', 'NUMERO_CENTROS',
       'NUMERO_CENTROS_PORCENTAJE', 'tipo', 'Lineas de metro',
       'Lineas de metrobus', 'Estaciones Ecobici', 'LineasRTP',
       'Lineas de metro_PORCENTAJE_MUN', 'Lineas de metrobus_PORCENTAJE_MUN',
       'Estaciones Ecobici_PORCENTAJE_MUN', 'LineasRTP_PORCENTAJE_MUN',
       'General_Security_SCORE', 'normalized'],
      dtype='object')

In [196]:
merged_data_percentage=merged_data[['ALCALDIA', 'venta_PORCENTAJE_MUN','Renta_PORCENTAJE_MUN','BUEN_EDO','Superficie (m²)_PORCENTAJE',
                                   'NUMERO_CENTROS_PORCENTAJE','tipo','Lineas de metro_PORCENTAJE_MUN', 'Lineas de metrobus_PORCENTAJE_MUN',
                                   'Estaciones Ecobici_PORCENTAJE_MUN', 'LineasRTP_PORCENTAJE_MUN',"normalized"]]

In [197]:
merged_data_percentage['PUBLIC_TRANSPORATION']=merged_data_percentage.iloc[:,7:11].mean(axis=1)
merged_data_percentage

C:\Users\Tan_y\AppData\Local\Temp\ipykernel_17712\2813283589.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_percentage['PUBLIC_TRANSPORATION']=merged_data_percentage.iloc[:,7:11].mean(axis=1)

,ALCALDIA,venta_PORCENTAJE_MUN,Renta_PORCENTAJE_MUN,BUEN_EDO,Superficie (m²)_PORCENTAJE,NUMERO_CENTROS_PORCENTAJE,tipo,Lineas de metro_PORCENTAJE_MUN,Lineas de metrobus_PORCENTAJE_MUN,Estaciones Ecobici_PORCENTAJE_MUN,LineasRTP_PORCENTAJE_MUN,normalized,PUBLIC_TRANSPORATION
0,Azcapotzalco,0.239483,0.535420,0.998924,0.059141,0.054326,0.030508,0.047619,0.066667,0.041359,0.035714,0.182243,0.047840
1,Benito Juárez,0.495751,0.717079,0.999721,0.013805,0.050302,0.136723,0.095238,0.100000,0.314623,0.071429,1.000000,0.145323
2,Coyoacán,0.603708,0.595522,0.999106,0.136047,0.054326,0.082486,0.047619,0.066667,0.054653,0.123016,0.495327,0.072989
3,Cuajimalpa de Morelos,0.825104,0.682685,0.996435,0.030440,0.028169,0.030508,0.000000,0.000000,0.000000,0.051587,0.607477,0.012897
4,Cuauhtémoc,0.533647,1.000000,0.999296,0.028464,0.140845,0.275706,0.166667,0.166667,0.358936,0.051587,0.607477,0.185964
5,Gustavo A. Madero,0.515525,0.425865,0.998361,0.116646,0.116700,0.047458,0.119048,0.166667,0.000000,0.071429,0.154206,0.089286
6,Iztacalco,0.270673,0.438959,0.999163,0.028885,0.022133,0.005650,0.119048,0.100000,0.000000,0.035714,0.257009,0.063690
7,Iztapalapa,0.423729,0.456506,0.998023,0.146109,0.130785,0.036158,0.071429,0.066667,0.000000,0.087302,0.102804,0.056349
8,La Magdalena Contreras,0.773432,0.509406,0.994765,0.019835,0.028169,0.007910,0.000000,0.000000,0.000000,0.019841,0.504673,0.004960
9,Miguel Hidalgo,1.000000,0.930819,0.999268,0.083310,0.054326,0.166102,0.095238,0.066667,0.205318,0.091270,0.630841,0.114623
10,Milpa Alta,0.375051,0.698355,0.967689,0.004601,0.032193,0.003390,0.000000,0.000000,0.000000,0.023810,0.453271,0.005952
11,Tlalpan,0.457364,0.698355,0.987721,0.097023,0.080483,0.041808,0.000000,0.066667,0.000000,0.095238,0.429907,0.040476
12,Tláhuac,0.270722,0.782943,0.990920,0.045372,0.042254,0.006780,0.023810,0.000000,0.000000,0.035714,0.000000,0.014881
13,Venustiano Carranza,0.477333,0.450264,0.999169,0.086243,0.060362,0.023729,0.142857,0.066667,0.000000,0.035714,0.476636,0.061310
14,Xochimilco,0.305528,0.662695,0.975280,0.031083,0.046278,0.005650,0.000000,0.033333,0.000000,0.059524,0.056075,0.023214
15,Álvaro Obregón,0.671721,0.667889,0.998248,0.072996,0.058350,0.099435,0.071429,0.033333,0.025111,0.111111,0.355140,0.060246

In [198]:
merged_data_percentage['HOUSING_PRICE']=merged_data_percentage.iloc[:,1:3].mean(axis=1)
merged_data_percentage

C:\Users\Tan_y\AppData\Local\Temp\ipykernel_17712\2582706021.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_percentage['HOUSING_PRICE']=merged_data_percentage.iloc[:,1:3].mean(axis=1)

,ALCALDIA,venta_PORCENTAJE_MUN,Renta_PORCENTAJE_MUN,BUEN_EDO,Superficie (m²)_PORCENTAJE,NUMERO_CENTROS_PORCENTAJE,tipo,Lineas de metro_PORCENTAJE_MUN,Lineas de metrobus_PORCENTAJE_MUN,Estaciones Ecobici_PORCENTAJE_MUN,LineasRTP_PORCENTAJE_MUN,normalized,PUBLIC_TRANSPORATION,HOUSING_PRICE
0,Azcapotzalco,0.239483,0.535420,0.998924,0.059141,0.054326,0.030508,0.047619,0.066667,0.041359,0.035714,0.182243,0.047840,0.387451
1,Benito Juárez,0.495751,0.717079,0.999721,0.013805,0.050302,0.136723,0.095238,0.100000,0.314623,0.071429,1.000000,0.145323,0.606415
2,Coyoacán,0.603708,0.595522,0.999106,0.136047,0.054326,0.082486,0.047619,0.066667,0.054653,0.123016,0.495327,0.072989,0.599615
3,Cuajimalpa de Morelos,0.825104,0.682685,0.996435,0.030440,0.028169,0.030508,0.000000,0.000000,0.000000,0.051587,0.607477,0.012897,0.753894
4,Cuauhtémoc,0.533647,1.000000,0.999296,0.028464,0.140845,0.275706,0.166667,0.166667,0.358936,0.051587,0.607477,0.185964,0.766823
5,Gustavo A. Madero,0.515525,0.425865,0.998361,0.116646,0.116700,0.047458,0.119048,0.166667,0.000000,0.071429,0.154206,0.089286,0.470695
6,Iztacalco,0.270673,0.438959,0.999163,0.028885,0.022133,0.005650,0.119048,0.100000,0.000000,0.035714,0.257009,0.063690,0.354816
7,Iztapalapa,0.423729,0.456506,0.998023,0.146109,0.130785,0.036158,0.071429,0.066667,0.000000,0.087302,0.102804,0.056349,0.440117
8,La Magdalena Contreras,0.773432,0.509406,0.994765,0.019835,0.028169,0.007910,0.000000,0.000000,0.000000,0.019841,0.504673,0.004960,0.641419
9,Miguel Hidalgo,1.000000,0.930819,0.999268,0.083310,0.054326,0.166102,0.095238,0.066667,0.205318,0.091270,0.630841,0.114623,0.965410
10,Milpa Alta,0.375051,0.698355,0.967689,0.004601,0.032193,0.003390,0.000000,0.000000,0.000000,0.023810,0.453271,0.005952,0.536703
11,Tlalpan,0.457364,0.698355,0.987721,0.097023,0.080483,0.041808,0.000000,0.066667,0.000000,0.095238,0.429907,0.040476,0.577859
12,Tláhuac,0.270722,0.782943,0.990920,0.045372,0.042254,0.006780,0.023810,0.000000,0.000000,0.035714,0.000000,0.014881,0.526832
13,Venustiano Carranza,0.477333,0.450264,0.999169,0.086243,0.060362,0.023729,0.142857,0.066667,0.000000,0.035714,0.476636,0.061310,0.463798
14,Xochimilco,0.305528,0.662695,0.975280,0.031083,0.046278,0.005650,0.000000,0.033333,0.000000,0.059524,0.056075,0.023214,0.484111
15,Álvaro Obregón,0.671721,0.667889,0.998248,0.072996,0.058350,0.099435,0.071429,0.033333,0.025111,0.111111,0.355140,0.060246,0.669805

In [199]:
percentage_alcaldia=merged_data_percentage[["Superficie (m²)_PORCENTAJE","BUEN_EDO","tipo","PUBLIC_TRANSPORATION","HOUSING_PRICE","normalized"]].mean(axis=1)

In [200]:
percentage_alcaldia

0     0.284351
1     0.483664
2     0.397595
3     0.405275
4     0.477288
5     0.312775
6     0.284869
7     0.296593
8     0.362260
9     0.493259
10    0.328601
11    0.362466
12    0.264131
13    0.351814
14    0.262569
15    0.375978
dtype: float64

In [201]:
filtered_alcaldia=pd.concat([merged_data_percentage["ALCALDIA"],percentage_alcaldia], axis=1)
filtered_alcaldia=filtered_alcaldia.rename(columns={0:"PORCENTAJE"})
filtered_alcaldia

                  ALCALDIA  PORCENTAJE
0             Azcapotzalco    0.284351
1            Benito Juárez    0.483664
2                 Coyoacán    0.397595
3    Cuajimalpa de Morelos    0.405275
4               Cuauhtémoc    0.477288
5        Gustavo A. Madero    0.312775
6                Iztacalco    0.284869
7               Iztapalapa    0.296593
8   La Magdalena Contreras    0.362260
9           Miguel Hidalgo    0.493259
10              Milpa Alta    0.328601
11                 Tlalpan    0.362466
12                 Tláhuac    0.264131
13     Venustiano Carranza    0.351814
14              Xochimilco    0.262569
15          Álvaro Obregón    0.375978

In [208]:
alcaldia_ranking= filtered_alcaldia.sort_values(by="PORCENTAJE", ascending=False).reset_index().drop("index", axis=1)
alcaldia_ranking

                  ALCALDIA  PORCENTAJE
0           Miguel Hidalgo    0.493259
1            Benito Juárez    0.483664
2               Cuauhtémoc    0.477288
3    Cuajimalpa de Morelos    0.405275
4                 Coyoacán    0.397595
5           Álvaro Obregón    0.375978
6                  Tlalpan    0.362466
7   La Magdalena Contreras    0.362260
8      Venustiano Carranza    0.351814
9               Milpa Alta    0.328601
10       Gustavo A. Madero    0.312775
11              Iztapalapa    0.296593
12               Iztacalco    0.284869
13            Azcapotzalco    0.284351
14                 Tláhuac    0.264131
15              Xochimilco    0.262569

In [209]:
alcaldia_ranking.to_csv("./output/ranking_quality.csv", index=False)