In [229]:
import pandas as pd
import numpy as np

In [230]:
df = pd.read_csv("./raw/tenement/conjunto_de_datos_iter_09CSV20.csv")

In [231]:
data= df[[ "NOM_MUN","NOM_LOC","POBTOT","POBFEM","POBMAS","P_18YMAS","P_18YMAS_F","P_18YMAS_M","P_60YMAS","P_60YMAS_F","P_60YMAS_M","P_18A24","P_18A24_F","P_18A24_M","P_25A29","P_25A29_F","P_25A29_M","PCON_DISC","P12YM_CASA","P12YM_SOLT","P12YM_SEPA","PCATOLICA","PRO_CRIEVA","POTRAS_REL","PSIN_RELIG","PROM_OCUP","VPH_PISODT","VPH_PISOTI","VPH_C_ELEC","VPH_S_ELEC","VPH_AEASP","VPH_AGUAFV","VPH_DRENAJ","VPH_NODREN","VPH_SNBIEN","VPH_REFRI","VPH_LAVAD","VPH_HMICRO","VPH_AUTOM","VPH_MOTO","VPH_BICI","VPH_RADIO","VPH_TV","VPH_PC","VPH_TELEF","VPH_CEL","VPH_INTER","VPH_STVP","VPH_SPMVPI","VPH_CVJ"]]
data

,NOM_MUN,NOM_LOC,POBTOT,POBFEM,POBMAS,P_18YMAS,P_18YMAS_F,P_18YMAS_M,P_60YMAS,P_60YMAS_F,...,VPH_BICI,VPH_RADIO,VPH_TV,VPH_PC,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ
0,Total de la entidad Ciudad de México,Total de la Entidad,9209944,4805017,4404927,7166737,3798760,3367977,1491619,853207,...,550349,2165974,2647911,1649403,1898265,2536523,2084156,1290811,957162,568827
1,Total de la entidad Ciudad de México,Localidades de una vivienda,320,128,192,227,89,138,37,11,...,11,66,61,20,24,67,23,17,8,8
2,Total de la entidad Ciudad de México,Localidades de dos viviendas,364,178,186,255,124,131,48,20,...,12,79,82,28,21,89,27,22,6,4
3,Azcapotzalco,Total del Municipio,432205,227255,204950,345123,184700,160423,78650,45565,...,33588,106789,130067,86856,96128,123961,105899,66399,50965,31801
4,Azcapotzalco,Azcapotzalco,432205,227255,204950,345123,184700,160423,78650,45565,...,33588,106789,130067,86856,96128,123961,105899,66399,50965,31801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
661,Cuauhtémoc,Cuauhtémoc,545884,284933,260951,444024,234635,209389,93809,55146,...,47753,151662,186150,130963,138201,183557,157682,98006,87040,45215
662,Miguel Hidalgo,Total del Municipio,414470,219003,195467,332956,178841,154115,71111,41605,...,31432,112959,139522,109631,109265,137103,124777,88559,77955,39658
663,Miguel Hidalgo,Miguel Hidalgo,414470,219003,195467,332956,178841,154115,71111,41605,...,31432,112959,139522,109631,109265,137103,124777,88559,77955,39658
664,Venustiano Carranza,Total del Municipio,443704,233586,210118,347576,186203,161373,78964,45947,...,28982,105631,131104,79437,92856,124244,102008,62293,44934,28376
665,Venustiano Carranza,Venustiano Carranza,443704,233586,210118,347576,186203,161373,78964,45947,...,28982,105631,131104,79437,92856,124244,102008,62293,44934,28376

In [232]:
data=data.query('NOM_LOC=="Total del Municipio" or NOM_LOC=="Total de la Entidad"').reset_index()
data

,index,NOM_MUN,NOM_LOC,POBTOT,POBFEM,POBMAS,P_18YMAS,P_18YMAS_F,P_18YMAS_M,P_60YMAS,...,VPH_BICI,VPH_RADIO,VPH_TV,VPH_PC,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ
0,0,Total de la entidad Ciudad de México,Total de la Entidad,9209944,4805017,4404927,7166737,3798760,3367977,1491619,...,550349,2165974,2647911,1649403,1898265,2536523,2084156,1290811,957162,568827
1,3,Azcapotzalco,Total del Municipio,432205,227255,204950,345123,184700,160423,78650,...,33588,106789,130067,86856,96128,123961,105899,66399,50965,31801
2,5,Coyoacán,Total del Municipio,614447,325337,289110,500374,269320,231054,126592,...,36902,154275,184451,133587,145013,179280,157908,101660,80413,44991
3,7,Cuajimalpa de Morelos,Total del Municipio,217686,113537,104149,162395,86322,76073,25803,...,5061,47367,58499,37693,42165,56543,46389,31667,24817,14591
4,34,Gustavo A. Madero,Total del Municipio,1173351,609477,563874,911482,480252,431230,203469,...,66256,264089,327503,185635,228113,306796,246278,143954,95131,60940
5,36,Iztacalco,Total del Municipio,404695,212343,192352,319021,170195,148826,70907,...,26960,92144,114018,72374,82298,108707,91039,53971,40298,25607
6,38,Iztapalapa,Total del Municipio,1835486,947835,887651,1383459,725294,658165,262064,...,111361,389145,484383,247057,323613,455216,349103,183804,116462,82472
7,40,La Magdalena Contreras,Total del Municipio,247622,129335,118287,189047,100355,88692,38073,...,5764,55272,65741,37699,48042,62286,50653,34426,21456,13357
8,66,Milpa Alta,Total del Municipio,152685,78314,74371,108278,56374,51904,16437,...,5670,30411,36675,13896,20252,33845,19798,8170,4273,3030
9,313,Álvaro Obregón,Total del Municipio,759137,398130,361007,590251,314600,275651,122319,...,20336,176390,211976,134949,154631,203151,169135,120733,83063,49379
10,322,Tláhuac,Total del Municipio,392313,202123,190190,288877,151415,137462,46196,...,38434,82506,101918,50871,64849,96419,71996,42449,22015,15852
11,377,Tlalpan,Total del Municipio,699928,365051,334877,539464,286134,253330,108894,...,21993,162465,194433,120475,137033,188352,151857,94253,69538,41272
12,544,Xochimilco,Total del Municipio,442178,226726,215452,332325,172725,159600,60987,...,33091,93953,111686,58591,74442,106703,77848,37859,26763,17813
13,658,Benito Juárez,Total del Municipio,434153,232032,202121,372085,201395,170690,87344,...,36766,140916,169785,149689,141364,170360,161786,122608,112039,54473
14,660,Cuauhtémoc,Total del Municipio,545884,284933,260951,444024,234635,209389,93809,...,47753,151662,186150,130963,138201,183557,157682,98006,87040,45215
15,662,Miguel Hidalgo,Total del Municipio,414470,219003,195467,332956,178841,154115,71111,...,31432,112959,139522,109631,109265,137103,124777,88559,77955,39658
16,664,Venustiano Carranza,Total del Municipio,443704,233586,210118,347576,186203,161373,78964,...,28982,105631,131104,79437,92856,124244,102008,62293,44934,28376

In [233]:
data=data.drop(["index","NOM_LOC"], axis=1)
data

,NOM_MUN,POBTOT,POBFEM,POBMAS,P_18YMAS,P_18YMAS_F,P_18YMAS_M,P_60YMAS,P_60YMAS_F,P_60YMAS_M,...,VPH_BICI,VPH_RADIO,VPH_TV,VPH_PC,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ
0,Total de la entidad Ciudad de México,9209944,4805017,4404927,7166737,3798760,3367977,1491619,853207,638412,...,550349,2165974,2647911,1649403,1898265,2536523,2084156,1290811,957162,568827
1,Azcapotzalco,432205,227255,204950,345123,184700,160423,78650,45565,33085,...,33588,106789,130067,86856,96128,123961,105899,66399,50965,31801
2,Coyoacán,614447,325337,289110,500374,269320,231054,126592,73584,53008,...,36902,154275,184451,133587,145013,179280,157908,101660,80413,44991
3,Cuajimalpa de Morelos,217686,113537,104149,162395,86322,76073,25803,14266,11537,...,5061,47367,58499,37693,42165,56543,46389,31667,24817,14591
4,Gustavo A. Madero,1173351,609477,563874,911482,480252,431230,203469,116135,87334,...,66256,264089,327503,185635,228113,306796,246278,143954,95131,60940
5,Iztacalco,404695,212343,192352,319021,170195,148826,70907,40949,29958,...,26960,92144,114018,72374,82298,108707,91039,53971,40298,25607
6,Iztapalapa,1835486,947835,887651,1383459,725294,658165,262064,146769,115295,...,111361,389145,484383,247057,323613,455216,349103,183804,116462,82472
7,La Magdalena Contreras,247622,129335,118287,189047,100355,88692,38073,21646,16427,...,5764,55272,65741,37699,48042,62286,50653,34426,21456,13357
8,Milpa Alta,152685,78314,74371,108278,56374,51904,16437,8767,7670,...,5670,30411,36675,13896,20252,33845,19798,8170,4273,3030
9,Álvaro Obregón,759137,398130,361007,590251,314600,275651,122319,69602,52717,...,20336,176390,211976,134949,154631,203151,169135,120733,83063,49379
10,Tláhuac,392313,202123,190190,288877,151415,137462,46196,25335,20861,...,38434,82506,101918,50871,64849,96419,71996,42449,22015,15852
11,Tlalpan,699928,365051,334877,539464,286134,253330,108894,61561,47333,...,21993,162465,194433,120475,137033,188352,151857,94253,69538,41272
12,Xochimilco,442178,226726,215452,332325,172725,159600,60987,33715,27272,...,33091,93953,111686,58591,74442,106703,77848,37859,26763,17813
13,Benito Juárez,434153,232032,202121,372085,201395,170690,87344,52615,34729,...,36766,140916,169785,149689,141364,170360,161786,122608,112039,54473
14,Cuauhtémoc,545884,284933,260951,444024,234635,209389,93809,55146,38663,...,47753,151662,186150,130963,138201,183557,157682,98006,87040,45215
15,Miguel Hidalgo,414470,219003,195467,332956,178841,154115,71111,41605,29506,...,31432,112959,139522,109631,109265,137103,124777,88559,77955,39658
16,Venustiano Carranza,443704,233586,210118,347576,186203,161373,78964,45947,33017,...,28982,105631,131104,79437,92856,124244,102008,62293,44934,28376

In [234]:
dr=data.iloc[:,0]
dr

0     Total de la entidad Ciudad de México
1                             Azcapotzalco
2                                 Coyoacán
3                    Cuajimalpa de Morelos
4                        Gustavo A. Madero
5                                Iztacalco
6                               Iztapalapa
7                   La Magdalena Contreras
8                               Milpa Alta
9                           Álvaro Obregón
10                                 Tláhuac
11                                 Tlalpan
12                              Xochimilco
13                           Benito Juárez
14                              Cuauhtémoc
15                          Miguel Hidalgo
16                     Venustiano Carranza
Name: NOM_MUN, dtype: object

In [235]:
dh=data.iloc[:,1:].apply(pd.to_numeric, errors="coerce")
dh

,POBTOT,POBFEM,POBMAS,P_18YMAS,P_18YMAS_F,P_18YMAS_M,P_60YMAS,P_60YMAS_F,P_60YMAS_M,P_18A24,...,VPH_BICI,VPH_RADIO,VPH_TV,VPH_PC,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ
0,9209944,4805017,4404927,7166737,3798760,3367977,1491619,853207,638412,984186,...,550349,2165974,2647911,1649403,1898265,2536523,2084156,1290811,957162,568827
1,432205,227255,204950,345123,184700,160423,78650,45565,33085,43088,...,33588,106789,130067,86856,96128,123961,105899,66399,50965,31801
2,614447,325337,289110,500374,269320,231054,126592,73584,53008,63817,...,36902,154275,184451,133587,145013,179280,157908,101660,80413,44991
3,217686,113537,104149,162395,86322,76073,25803,14266,11537,25202,...,5061,47367,58499,37693,42165,56543,46389,31667,24817,14591
4,1173351,609477,563874,911482,480252,431230,203469,116135,87334,126620,...,66256,264089,327503,185635,228113,306796,246278,143954,95131,60940
5,404695,212343,192352,319021,170195,148826,70907,40949,29958,42216,...,26960,92144,114018,72374,82298,108707,91039,53971,40298,25607
6,1835486,947835,887651,1383459,725294,658165,262064,146769,115295,209136,...,111361,389145,484383,247057,323613,455216,349103,183804,116462,82472
7,247622,129335,118287,189047,100355,88692,38073,21646,16427,27704,...,5764,55272,65741,37699,48042,62286,50653,34426,21456,13357
8,152685,78314,74371,108278,56374,51904,16437,8767,7670,18754,...,5670,30411,36675,13896,20252,33845,19798,8170,4273,3030
9,759137,398130,361007,590251,314600,275651,122319,69602,52717,82778,...,20336,176390,211976,134949,154631,203151,169135,120733,83063,49379
10,392313,202123,190190,288877,151415,137462,46196,25335,20861,46722,...,38434,82506,101918,50871,64849,96419,71996,42449,22015,15852
11,699928,365051,334877,539464,286134,253330,108894,61561,47333,79747,...,21993,162465,194433,120475,137033,188352,151857,94253,69538,41272
12,442178,226726,215452,332325,172725,159600,60987,33715,27272,51340,...,33091,93953,111686,58591,74442,106703,77848,37859,26763,17813
13,434153,232032,202121,372085,201395,170690,87344,52615,34729,33294,...,36766,140916,169785,149689,141364,170360,161786,122608,112039,54473
14,545884,284933,260951,444024,234635,209389,93809,55146,38663,51762,...,47753,151662,186150,130963,138201,183557,157682,98006,87040,45215
15,414470,219003,195467,332956,178841,154115,71111,41605,29506,36545,...,31432,112959,139522,109631,109265,137103,124777,88559,77955,39658
16,443704,233586,210118,347576,186203,161373,78964,45947,33017,45461,...,28982,105631,131104,79437,92856,124244,102008,62293,44934,28376

In [236]:
data=pd.concat([dr,dh],axis=1)
data

,NOM_MUN,POBTOT,POBFEM,POBMAS,P_18YMAS,P_18YMAS_F,P_18YMAS_M,P_60YMAS,P_60YMAS_F,P_60YMAS_M,...,VPH_BICI,VPH_RADIO,VPH_TV,VPH_PC,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ
0,Total de la entidad Ciudad de México,9209944,4805017,4404927,7166737,3798760,3367977,1491619,853207,638412,...,550349,2165974,2647911,1649403,1898265,2536523,2084156,1290811,957162,568827
1,Azcapotzalco,432205,227255,204950,345123,184700,160423,78650,45565,33085,...,33588,106789,130067,86856,96128,123961,105899,66399,50965,31801
2,Coyoacán,614447,325337,289110,500374,269320,231054,126592,73584,53008,...,36902,154275,184451,133587,145013,179280,157908,101660,80413,44991
3,Cuajimalpa de Morelos,217686,113537,104149,162395,86322,76073,25803,14266,11537,...,5061,47367,58499,37693,42165,56543,46389,31667,24817,14591
4,Gustavo A. Madero,1173351,609477,563874,911482,480252,431230,203469,116135,87334,...,66256,264089,327503,185635,228113,306796,246278,143954,95131,60940
5,Iztacalco,404695,212343,192352,319021,170195,148826,70907,40949,29958,...,26960,92144,114018,72374,82298,108707,91039,53971,40298,25607
6,Iztapalapa,1835486,947835,887651,1383459,725294,658165,262064,146769,115295,...,111361,389145,484383,247057,323613,455216,349103,183804,116462,82472
7,La Magdalena Contreras,247622,129335,118287,189047,100355,88692,38073,21646,16427,...,5764,55272,65741,37699,48042,62286,50653,34426,21456,13357
8,Milpa Alta,152685,78314,74371,108278,56374,51904,16437,8767,7670,...,5670,30411,36675,13896,20252,33845,19798,8170,4273,3030
9,Álvaro Obregón,759137,398130,361007,590251,314600,275651,122319,69602,52717,...,20336,176390,211976,134949,154631,203151,169135,120733,83063,49379
10,Tláhuac,392313,202123,190190,288877,151415,137462,46196,25335,20861,...,38434,82506,101918,50871,64849,96419,71996,42449,22015,15852
11,Tlalpan,699928,365051,334877,539464,286134,253330,108894,61561,47333,...,21993,162465,194433,120475,137033,188352,151857,94253,69538,41272
12,Xochimilco,442178,226726,215452,332325,172725,159600,60987,33715,27272,...,33091,93953,111686,58591,74442,106703,77848,37859,26763,17813
13,Benito Juárez,434153,232032,202121,372085,201395,170690,87344,52615,34729,...,36766,140916,169785,149689,141364,170360,161786,122608,112039,54473
14,Cuauhtémoc,545884,284933,260951,444024,234635,209389,93809,55146,38663,...,47753,151662,186150,130963,138201,183557,157682,98006,87040,45215
15,Miguel Hidalgo,414470,219003,195467,332956,178841,154115,71111,41605,29506,...,31432,112959,139522,109631,109265,137103,124777,88559,77955,39658
16,Venustiano Carranza,443704,233586,210118,347576,186203,161373,78964,45947,33017,...,28982,105631,131104,79437,92856,124244,102008,62293,44934,28376

In [237]:
nombres_alcaldias=data.iloc[:,0]
nombres_alcaldias

0     Total de la entidad Ciudad de México
1                             Azcapotzalco
2                                 Coyoacán
3                    Cuajimalpa de Morelos
4                        Gustavo A. Madero
5                                Iztacalco
6                               Iztapalapa
7                   La Magdalena Contreras
8                               Milpa Alta
9                           Álvaro Obregón
10                                 Tláhuac
11                                 Tlalpan
12                              Xochimilco
13                           Benito Juárez
14                              Cuauhtémoc
15                          Miguel Hidalgo
16                     Venustiano Carranza
Name: NOM_MUN, dtype: object

### Poblacion edades

In [332]:
poblacion_y_edad=data.iloc[:,:16]
poblacion_y_edad

,NOM_MUN,POBTOT,POBFEM,POBMAS,P_18YMAS,P_18YMAS_F,P_18YMAS_M,P_60YMAS,P_60YMAS_F,P_60YMAS_M,P_18A24,P_18A24_F,P_18A24_M,P_25A29,P_25A29_F,P_25A29_M
0,Total de la entidad Ciudad de México,9209944,4805017,4404927,7166737,3798760,3367977,1491619,853207,638412,984186,487898,496288,752289,380208,372081
1,Azcapotzalco,432205,227255,204950,345123,184700,160423,78650,45565,33085,43088,21303,21785,34405,17506,16899
2,Coyoacán,614447,325337,289110,500374,269320,231054,126592,73584,53008,63817,31569,32248,47839,23960,23879
3,Cuajimalpa de Morelos,217686,113537,104149,162395,86322,76073,25803,14266,11537,25202,12908,12294,18450,9718,8732
4,Gustavo A. Madero,1173351,609477,563874,911482,480252,431230,203469,116135,87334,126620,61797,64823,91448,45079,46369
5,Iztacalco,404695,212343,192352,319021,170195,148826,70907,40949,29958,42216,20935,21281,31727,16154,15573
6,Iztapalapa,1835486,947835,887651,1383459,725294,658165,262064,146769,115295,209136,103444,105692,151590,76092,75498
7,La Magdalena Contreras,247622,129335,118287,189047,100355,88692,38073,21646,16427,27704,13771,13933,19833,10070,9763
8,Milpa Alta,152685,78314,74371,108278,56374,51904,16437,8767,7670,18754,9229,9525,12949,6646,6303
9,Álvaro Obregón,759137,398130,361007,590251,314600,275651,122319,69602,52717,82778,41501,41277,60708,31159,29549
10,Tláhuac,392313,202123,190190,288877,151415,137462,46196,25335,20861,46722,23017,23705,33430,16937,16493
11,Tlalpan,699928,365051,334877,539464,286134,253330,108894,61561,47333,79747,39291,40456,56410,28601,27809
12,Xochimilco,442178,226726,215452,332325,172725,159600,60987,33715,27272,51340,25450,25890,36563,17952,18611
13,Benito Juárez,434153,232032,202121,372085,201395,170690,87344,52615,34729,33294,16744,16550,37175,19331,17844
14,Cuauhtémoc,545884,284933,260951,444024,234635,209389,93809,55146,38663,51762,25874,25888,50171,25150,25021
15,Miguel Hidalgo,414470,219003,195467,332956,178841,154115,71111,41605,29506,36545,18619,17926,34671,18160,16511
16,Venustiano Carranza,443704,233586,210118,347576,186203,161373,78964,45947,33017,45461,22446,23015,34920,17693,17227

In [333]:
for r in range(1,15+1,3):
    for i in range(0,2+1):
        index=poblacion_y_edad.columns[r+i]
        poblacion_y_edad[index+"_PORCENTAJE_MUN"]=poblacion_y_edad[index]/poblacion_y_edad[poblacion_y_edad.columns[r]]
poblacion_y_edad

,NOM_MUN,POBTOT,POBFEM,POBMAS,P_18YMAS,P_18YMAS_F,P_18YMAS_M,P_60YMAS,P_60YMAS_F,P_60YMAS_M,...,P_18YMAS_M_PORCENTAJE_MUN,P_60YMAS_PORCENTAJE_MUN,P_60YMAS_F_PORCENTAJE_MUN,P_60YMAS_M_PORCENTAJE_MUN,P_18A24_PORCENTAJE_MUN,P_18A24_F_PORCENTAJE_MUN,P_18A24_M_PORCENTAJE_MUN,P_25A29_PORCENTAJE_MUN,P_25A29_F_PORCENTAJE_MUN,P_25A29_M_PORCENTAJE_MUN
0,Total de la entidad Ciudad de México,9209944,4805017,4404927,7166737,3798760,3367977,1491619,853207,638412,...,0.469946,1.0,0.572001,0.427999,1.0,0.495738,0.504262,1.0,0.505402,0.494598
1,Azcapotzalco,432205,227255,204950,345123,184700,160423,78650,45565,33085,...,0.464828,1.0,0.579339,0.420661,1.0,0.494407,0.505593,1.0,0.508821,0.491179
2,Coyoacán,614447,325337,289110,500374,269320,231054,126592,73584,53008,...,0.461763,1.0,0.581269,0.418731,1.0,0.494680,0.505320,1.0,0.500847,0.499153
3,Cuajimalpa de Morelos,217686,113537,104149,162395,86322,76073,25803,14266,11537,...,0.468444,1.0,0.552881,0.447119,1.0,0.512182,0.487818,1.0,0.526721,0.473279
4,Gustavo A. Madero,1173351,609477,563874,911482,480252,431230,203469,116135,87334,...,0.473109,1.0,0.570775,0.429225,1.0,0.488051,0.511949,1.0,0.492947,0.507053
5,Iztacalco,404695,212343,192352,319021,170195,148826,70907,40949,29958,...,0.466508,1.0,0.577503,0.422497,1.0,0.495902,0.504098,1.0,0.509156,0.490844
6,Iztapalapa,1835486,947835,887651,1383459,725294,658165,262064,146769,115295,...,0.475739,1.0,0.560050,0.439950,1.0,0.494626,0.505374,1.0,0.501959,0.498041
7,La Magdalena Contreras,247622,129335,118287,189047,100355,88692,38073,21646,16427,...,0.469153,1.0,0.568539,0.431461,1.0,0.497076,0.502924,1.0,0.507740,0.492260
8,Milpa Alta,152685,78314,74371,108278,56374,51904,16437,8767,7670,...,0.479359,1.0,0.533370,0.466630,1.0,0.492108,0.507892,1.0,0.513244,0.486756
9,Álvaro Obregón,759137,398130,361007,590251,314600,275651,122319,69602,52717,...,0.467006,1.0,0.569020,0.430980,1.0,0.501353,0.498647,1.0,0.513260,0.486740
10,Tláhuac,392313,202123,190190,288877,151415,137462,46196,25335,20861,...,0.475850,1.0,0.548424,0.451576,1.0,0.492637,0.507363,1.0,0.506641,0.493359
11,Tlalpan,699928,365051,334877,539464,286134,253330,108894,61561,47333,...,0.469596,1.0,0.565330,0.434670,1.0,0.492696,0.507304,1.0,0.507020,0.492980
12,Xochimilco,442178,226726,215452,332325,172725,159600,60987,33715,27272,...,0.480253,1.0,0.552823,0.447177,1.0,0.495715,0.504285,1.0,0.490988,0.509012
13,Benito Juárez,434153,232032,202121,372085,201395,170690,87344,52615,34729,...,0.458739,1.0,0.602388,0.397612,1.0,0.502913,0.497087,1.0,0.520000,0.480000
14,Cuauhtémoc,545884,284933,260951,444024,234635,209389,93809,55146,38663,...,0.471571,1.0,0.587854,0.412146,1.0,0.499865,0.500135,1.0,0.501286,0.498714
15,Miguel Hidalgo,414470,219003,195467,332956,178841,154115,71111,41605,29506,...,0.462869,1.0,0.585071,0.414929,1.0,0.509481,0.490519,1.0,0.523781,0.476219
16,Venustiano Carranza,443704,233586,210118,347576,186203,161373,78964,45947,33017,...,0.464281,1.0,0.581873,0.418127,1.0,0.493742,0.506258,1.0,0.506672,0.493328

In [334]:
poblacion_y_edad.to_csv("./output/ages.csv", index=False)

### Poblacion casada

In [239]:
poblacion_casada=data.iloc[:,17:20]
poblacion_casada=pd.concat([nombres_alcaldias,poblacion_casada], axis=1)
poblacion_casada

                                 NOM_MUN  P12YM_CASA  P12YM_SOLT  P12YM_SEPA
0   Total de la entidad Ciudad de México     3731096     3017529     1160556
1                           Azcapotzalco      171393      147260       58399
2                               Coyoacán      247186      214160       82270
3                  Cuajimalpa de Morelos       92967       67268       21046
4                      Gustavo A. Madero      463694      385423      158203
5                              Iztacalco      158916      134768       56731
6                             Iztapalapa      748864      576503      224877
7                 La Magdalena Contreras      103562       75481       31647
8                             Milpa Alta       66737       41940       15673
9                         Álvaro Obregón      312904      245501       93468
10                               Tláhuac      165051      116646       45138
11                               Tlalpan      295011      221177       83342
12                            Xochimilco      189809      132266       50950
13                         Benito Juárez      176932      161564       54507
14                            Cuauhtémoc      203930      204264       71473
15                        Miguel Hidalgo      163915      144097       50462
16                   Venustiano Carranza      170225      149211       62370

In [240]:
total_municipal=poblacion_casada.iloc[:,1:4].sum(axis=1)
for i in range(1,len(poblacion_casada.columns)):
    index=poblacion_casada.columns[i]
    poblacion_casada[index+"_PORCENTAJE_MUN"]=poblacion_casada[index]/total_municipal
poblacion_casada

,NOM_MUN,P12YM_CASA,P12YM_SOLT,P12YM_SEPA,P12YM_CASA_PORCENTAJE_MUN,P12YM_SOLT_PORCENTAJE_MUN,P12YM_SEPA_PORCENTAJE_MUN
0,Total de la entidad Ciudad de México,3731096,3017529,1160556,0.471742,0.381522,0.146735
1,Azcapotzalco,171393,147260,58399,0.454561,0.390556,0.154883
2,Coyoacán,247186,214160,82270,0.454707,0.393955,0.151338
3,Cuajimalpa de Morelos,92967,67268,21046,0.512834,0.371070,0.116096
4,Gustavo A. Madero,463694,385423,158203,0.460324,0.382622,0.157053
5,Iztacalco,158916,134768,56731,0.453508,0.384595,0.161897
6,Iztapalapa,748864,576503,224877,0.483062,0.371879,0.145059
7,La Magdalena Contreras,103562,75481,31647,0.491537,0.358256,0.150206
8,Milpa Alta,66737,41940,15673,0.536687,0.337274,0.126039
9,Álvaro Obregón,312904,245501,93468,0.480008,0.376609,0.143384
10,Tláhuac,165051,116646,45138,0.504998,0.356896,0.138106
11,Tlalpan,295011,221177,83342,0.492070,0.368917,0.139012
12,Xochimilco,189809,132266,50950,0.508837,0.354577,0.136586
13,Benito Juárez,176932,161564,54507,0.450205,0.411101,0.138694
14,Cuauhtémoc,203930,204264,71473,0.425149,0.425845,0.149005
15,Miguel Hidalgo,163915,144097,50462,0.457258,0.401973,0.140769
16,Venustiano Carranza,170225,149211,62370,0.445842,0.390803,0.163355

In [335]:
poblacion_casada.to_csv("./output/married.csv", index=False)

### Poblacion religiosa

In [241]:
poblacion_religiosa=data.iloc[:,20:24]
poblacion_religiosa=pd.concat([nombres_alcaldias,poblacion_religiosa], axis=1)
poblacion_religiosa

,NOM_MUN,PCATOLICA,PRO_CRIEVA,POTRAS_REL,PSIN_RELIG
0,Total de la entidad Ciudad de México,6988016,668246,55245,1472848
1,Azcapotzalco,335663,29623,2171,63846
2,Coyoacán,463550,39559,2881,106925
3,Cuajimalpa de Morelos,174811,10285,5082,26667
4,Gustavo A. Madero,901136,90812,4796,174901
5,Iztacalco,307375,32436,1938,62204
6,Iztapalapa,1384540,154092,6142,288659
7,La Magdalena Contreras,199259,13065,1168,33374
8,Milpa Alta,117841,10820,243,23565
9,Álvaro Obregón,608016,41833,2767,103417
10,Tláhuac,297513,33237,923,60125
11,Tlalpan,531983,52851,2478,111218
12,Xochimilco,343974,32610,1297,63640
13,Benito Juárez,305323,24493,4132,99203
14,Cuauhtémoc,378996,40236,5277,119709
15,Miguel Hidalgo,300662,24676,11228,70497
16,Venustiano Carranza,337374,37618,2722,64898

In [242]:
total_municipal=poblacion_religiosa.iloc[:,1:5].sum(axis=1)
for i in range(1,len(poblacion_religiosa.columns)):
    index=poblacion_religiosa.columns[i]
    poblacion_religiosa[index+"_PORCENTAJE_MUN"]=poblacion_religiosa[index]/total_municipal
poblacion_religiosa

,NOM_MUN,PCATOLICA,PRO_CRIEVA,POTRAS_REL,PSIN_RELIG,PCATOLICA_PORCENTAJE_MUN,PRO_CRIEVA_PORCENTAJE_MUN,POTRAS_REL_PORCENTAJE_MUN,PSIN_RELIG_PORCENTAJE_MUN
0,Total de la entidad Ciudad de México,6988016,668246,55245,1472848,0.760861,0.072759,0.006015,0.160365
1,Azcapotzalco,335663,29623,2171,63846,0.778253,0.068683,0.005034,0.148031
2,Coyoacán,463550,39559,2881,106925,0.756304,0.064542,0.004700,0.174453
3,Cuajimalpa de Morelos,174811,10285,5082,26667,0.806156,0.047430,0.023436,0.122977
4,Gustavo A. Madero,901136,90812,4796,174901,0.769120,0.077508,0.004093,0.149278
5,Iztacalco,307375,32436,1938,62204,0.760918,0.080296,0.004798,0.153988
6,Iztapalapa,1384540,154092,6142,288659,0.755163,0.084046,0.003350,0.157442
7,La Magdalena Contreras,199259,13065,1168,33374,0.807154,0.052923,0.004731,0.135191
8,Milpa Alta,117841,10820,243,23565,0.772885,0.070965,0.001594,0.154556
9,Álvaro Obregón,608016,41833,2767,103417,0.804219,0.055332,0.003660,0.136789
10,Tláhuac,297513,33237,923,60125,0.759353,0.084832,0.002356,0.153459
11,Tlalpan,531983,52851,2478,111218,0.761575,0.075660,0.003547,0.159217
12,Xochimilco,343974,32610,1297,63640,0.779066,0.073858,0.002938,0.144138
13,Benito Juárez,305323,24493,4132,99203,0.704888,0.056546,0.009539,0.229026
14,Cuauhtémoc,378996,40236,5277,119709,0.696405,0.073934,0.009696,0.219965
15,Miguel Hidalgo,300662,24676,11228,70497,0.738613,0.060620,0.027583,0.173184
16,Venustiano Carranza,337374,37618,2722,64898,0.762234,0.084991,0.006150,0.146625

In [243]:
poblacion_religiosa.to_csv("./output/religion.csv", index=False)

### Estado de vivienda, bienes y proporción de personas por vivienda

In [304]:
estado_vivienda=data.iloc[:,24:]
estado_vivienda=pd.concat([nombres_alcaldias,estado_vivienda],axis=1)
estado_vivienda

,NOM_MUN,PROM_OCUP,VPH_PISODT,VPH_PISOTI,VPH_C_ELEC,VPH_S_ELEC,VPH_AEASP,VPH_AGUAFV,VPH_DRENAJ,VPH_NODREN,...,VPH_BICI,VPH_RADIO,VPH_TV,VPH_PC,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ
0,Total de la entidad Ciudad de México,3.32,2732051,16199,2746872,1917,2655528,29004,2744306,4207,...,550349,2165974,2647911,1649403,1898265,2536523,2084156,1290811,957162,568827
1,Azcapotzalco,3.21,133490,334,133798,38,132706,239,133748,87,...,33588,106789,130067,86856,96128,123961,105899,66399,50965,31801
2,Coyoacán,3.20,190701,450,191126,61,190474,133,190986,182,...,36902,154275,184451,133587,145013,179280,157908,101660,80413,44991
3,Cuajimalpa de Morelos,3.60,59692,591,60308,31,56005,285,60144,137,...,5061,47367,58499,37693,42165,56543,46389,31667,24817,14591
4,Gustavo A. Madero,3.42,338175,1466,339504,160,336452,755,339341,298,...,66256,264089,327503,185635,228113,306796,246278,143954,95131,60940
5,Iztacalco,3.43,117149,282,117396,52,116564,93,117387,42,...,26960,92144,114018,72374,82298,108707,91039,53971,40298,25607
6,Iztapalapa,3.61,500645,2872,503261,300,495107,1278,503213,327,...,111361,389145,484383,247057,323613,455216,349103,183804,116462,82472
7,La Magdalena Contreras,3.62,67362,618,67911,76,64656,802,67748,231,...,5764,55272,65741,37699,48042,62286,50653,34426,21456,13357
8,Milpa Alta,3.90,38001,1027,38879,151,31655,4107,38425,605,...,5670,30411,36675,13896,20252,33845,19798,8170,4273,3030
9,Álvaro Obregón,3.45,217550,1153,218704,74,215911,417,218480,220,...,20336,176390,211976,134949,154631,203151,169135,120733,83063,49379
10,Tláhuac,3.67,104766,1908,106424,243,100130,2291,106400,262,...,38434,82506,101918,50871,64849,96419,71996,42449,22015,15852
11,Tlalpan,3.44,200099,1801,201635,274,167425,8373,201251,649,...,21993,162465,194433,120475,137033,188352,151857,94253,69538,41272
12,Xochimilco,3.74,114202,2741,116707,248,98535,9821,116144,809,...,33091,93953,111686,58591,74442,106703,77848,37859,26763,17813
13,Benito Juárez,2.46,175564,129,175762,29,175492,43,175751,33,...,36766,140916,169785,149689,141364,170360,161786,122608,112039,54473
14,Cuauhtémoc,2.75,195486,256,195726,82,195261,183,195673,131,...,47753,151662,186150,130963,138201,183557,157682,98006,87040,45215
15,Miguel Hidalgo,2.81,144245,228,144483,45,144171,109,144398,129,...,31432,112959,139522,109631,109265,137103,124777,88559,77955,39658
16,Venustiano Carranza,3.26,134924,343,135248,53,134984,75,135217,65,...,28982,105631,131104,79437,92856,124244,102008,62293,44934,28376

In [305]:
buen_edo_suelo=estado_vivienda['VPH_PISODT']/(estado_vivienda['VPH_PISODT']+estado_vivienda['VPH_PISOTI'])
buen_edo_electricidad=estado_vivienda['VPH_C_ELEC']/(estado_vivienda['VPH_C_ELEC']+estado_vivienda['VPH_S_ELEC'])
buen_edo_agua=estado_vivienda['VPH_AEASP']/(estado_vivienda['VPH_AEASP']+estado_vivienda['VPH_AGUAFV'])
buen_edo_drenaje=estado_vivienda['VPH_DRENAJ']/(estado_vivienda['VPH_DRENAJ']+estado_vivienda['VPH_NODREN'])
buen_edo_bienes=estado_vivienda[['VPH_REFRI', 'VPH_LAVAD', 'VPH_HMICRO', 'VPH_AUTOM','VPH_MOTO', 'VPH_BICI', 'VPH_RADIO', 'VPH_TV', 'VPH_PC', 'VPH_TELEF','VPH_CEL', 'VPH_INTER', 'VPH_STVP', 'VPH_SPMVPI', 'VPH_CVJ']].sum(axis=1)/(estado_vivienda['VPH_SNBIEN']+estado_vivienda[['VPH_REFRI', 'VPH_LAVAD', 'VPH_HMICRO', 'VPH_AUTOM','VPH_MOTO', 'VPH_BICI', 'VPH_RADIO', 'VPH_TV', 'VPH_PC', 'VPH_TELEF','VPH_CEL', 'VPH_INTER', 'VPH_STVP', 'VPH_SPMVPI', 'VPH_CVJ']].sum(axis=1))

buen_edo_general=((buen_edo_suelo+buen_edo_electricidad+buen_edo_agua+buen_edo_drenaje+buen_edo_bienes)/5)

In [324]:
estado_vivienda["BUEN_EDO"]=buen_edo_general

In [325]:
estado_vivienda

,NOM_MUN,PROM_OCUP,VPH_PISODT,VPH_PISOTI,VPH_C_ELEC,VPH_S_ELEC,VPH_AEASP,VPH_AGUAFV,VPH_DRENAJ,VPH_NODREN,...,VPH_RADIO,VPH_TV,VPH_PC,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,BUEN_EDO
0,Total de la entidad Ciudad de México,3.32,2732051,16199,2746872,1917,2655528,29004,2744306,4207,...,2165974,2647911,1649403,1898265,2536523,2084156,1290811,957162,568827,0.996164
1,Azcapotzalco,3.21,133490,334,133798,38,132706,239,133748,87,...,106789,130067,86856,96128,123961,105899,66399,50965,31801,0.998924
2,Coyoacán,3.20,190701,450,191126,61,190474,133,190986,182,...,154275,184451,133587,145013,179280,157908,101660,80413,44991,0.999106
3,Cuajimalpa de Morelos,3.60,59692,591,60308,31,56005,285,60144,137,...,47367,58499,37693,42165,56543,46389,31667,24817,14591,0.996435
4,Gustavo A. Madero,3.42,338175,1466,339504,160,336452,755,339341,298,...,264089,327503,185635,228113,306796,246278,143954,95131,60940,0.998361
5,Iztacalco,3.43,117149,282,117396,52,116564,93,117387,42,...,92144,114018,72374,82298,108707,91039,53971,40298,25607,0.999163
6,Iztapalapa,3.61,500645,2872,503261,300,495107,1278,503213,327,...,389145,484383,247057,323613,455216,349103,183804,116462,82472,0.998023
7,La Magdalena Contreras,3.62,67362,618,67911,76,64656,802,67748,231,...,55272,65741,37699,48042,62286,50653,34426,21456,13357,0.994765
8,Milpa Alta,3.90,38001,1027,38879,151,31655,4107,38425,605,...,30411,36675,13896,20252,33845,19798,8170,4273,3030,0.967689
9,Álvaro Obregón,3.45,217550,1153,218704,74,215911,417,218480,220,...,176390,211976,134949,154631,203151,169135,120733,83063,49379,0.998248
10,Tláhuac,3.67,104766,1908,106424,243,100130,2291,106400,262,...,82506,101918,50871,64849,96419,71996,42449,22015,15852,0.990920
11,Tlalpan,3.44,200099,1801,201635,274,167425,8373,201251,649,...,162465,194433,120475,137033,188352,151857,94253,69538,41272,0.987721
12,Xochimilco,3.74,114202,2741,116707,248,98535,9821,116144,809,...,93953,111686,58591,74442,106703,77848,37859,26763,17813,0.975280
13,Benito Juárez,2.46,175564,129,175762,29,175492,43,175751,33,...,140916,169785,149689,141364,170360,161786,122608,112039,54473,0.999721
14,Cuauhtémoc,2.75,195486,256,195726,82,195261,183,195673,131,...,151662,186150,130963,138201,183557,157682,98006,87040,45215,0.999296
15,Miguel Hidalgo,2.81,144245,228,144483,45,144171,109,144398,129,...,112959,139522,109631,109265,137103,124777,88559,77955,39658,0.999268
16,Venustiano Carranza,3.26,134924,343,135248,53,134984,75,135217,65,...,105631,131104,79437,92856,124244,102008,62293,44934,28376,0.999169

In [336]:
estado_vivienda.to_csv("./output/housing_state.csv", index=False)